[package]
name = "irisv2-mcu"
edition = "2021"
version = "0.1.0"

[[bin]]
name = "main"
test = false
bench = false

[lib]
name = "lib"
test = false
bench = false

[dependencies]
cortex-m = { version = "0.7.8", features = ["critical-section-single-core", "inline-asm", "linker-plugin-lto"] }
defmt = { version = "1.1.1", features = ["encoding-rzcobs", "avoid-default-panic"] }
defmt-rtt = { version = "1.3.0" }
panic-probe = { version = "1.0.0", features = ["print-defmt"] }
rtic = { version = "2.3.0", features = [ "thumbv8main-backend" ] }
# just the hal from embassy, seems to be the most complete one
embassy-stm32 = { version = "0.6.0", features = [ "stm32h563vi", "defmt", "memory-x", "unstable-pac", "exti"] }
# pin the pac version
stm32-metapac = { version = "21.0.0", features = [ "stm32h563vi", "metadata" ] }
rtic-monotonics = { version = "2.2.1", features = ["stm32h563vi", "stm32_tim5"] }
talc =  { version = "5.0.4", features = [] }
spinning_top = { version = "0.3.0", features = [] }
embassy-embedded-hal = "0.6.0"
heapless = { version = "0.9.3", features = ["defmt", "portable-atomic-critical-section"] }

# cargo build/run
[profile.dev]
codegen-units = 8
debug = "full"
debug-assertions = true
incremental = true
opt-level = 2
lto = "thin"
overflow-checks = true

# cargo build/run --release
[profile.release]
codegen-units = 1
debug = "full"
debug-assertions = false
incremental = false
lto = 'fat'
opt-level = 3
overflow-checks = false